### ISSUE TITLE
twiddle_factors_256_br.h

### ISSUE THREAD

**Issue by skywalker45** [olewolf/geophone#1]
Hey olewolf, great work with the geophone, i just have a little problem. Before i go on, I'll like to specify what I'm working with. 
Arduino version: 1.6.8
OS: windows 7
these are the errors i get back when i try to verify the geophone.ino 
In file included from C:\Users\WKUUSER\Documents\geophone-master\Geophone\Geophone.ino:98:0:

C:\Users\WKUUSER\Documents\Arduino\libraries\geophone-master/twiddle_factors_256_br.h:10:7: error: 'prog_int16_t' does not name a type

 const prog_int16_t twiddle_real[ 256 ] PROGMEM =

```
   ^
```

C:\Users\WKUUSER\Documents\Arduino\libraries\geophone-master/twiddle_factors_256_br.h:46:7: error: 'prog_int16_t' does not name a type

 const prog_int16_t twiddle_imag[ 256 ] PROGMEM =

```
   ^
```

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28:0,

```
             from sketch\Geophone.ino.cpp:1:
```

C:\Users\WKUUSER\Documents\geophone-master\Geophone\Geophone.ino: In function 'void fft_radix2_512(short int_, short int_)':

Geophone:465: error: 'twiddle_real' was not declared in this scope

```
   short WR = pgm_read_word_near( twiddle_real + group );

                                  ^
```

Geophone:466: error: 'twiddle_imag' was not declared in this scope

```
   short WI = pgm_read_word_near( twiddle_imag + group );

                                  ^
```

exit status 1
'twiddle_real' was not declared in this scope

i realized it's something with the twiddle code, so i went ahead to take a look. 
on the 10th line, const prog_int16_t twiddle_real[ 256 ] PROGMEM =
prog_int16_t isnt recognized even when described. 

Any help would be appreciated

**Comment by olewolf** [comment]
Looks like this may be caused by a compiler change. Try and change the lines to:

`const int16_t twiddle_real[ 256 ] PROGMEM =`

and

`const int16_t twiddle_imag[ 256 ] PROGMEM =`

and see if that works.

**Comment by skywalker45** [comment]
wow, thank you for the prompt reply, i had just made the change before seeing this. Thank you again.
