### ISSUE TITLE
Few questions about design

### ISSUE THREAD

**Issue by sselbe** [olewolf/geophone#4]
I was building this circuit on a breadboard and not the Arduino shield approach that you documented here.  If running on Mega, can you just leave out the diodes and just run the signal out similar to the DiscoverCircuits example you referenced? There was a 100n capacitor you added to yours, what was the purpose and is that necessary?

Also, if connecting to three geophones to get all three axis, would you just build three amps and connect each to different analog pins? Or is there a better approach to get the best sampling freq?

**Comment by olewolf** [comment]
The diodes are there to protect the input of the Arduino but they aren't really necessary as long as the op-amp is powered with the same voltage as the Arduino can tolerate on its analog inputs. So, you'll probably be safe omitting the diodes.

I assume you're referring to capacitor C11. This is a decoupling capacitor that one should always place very close to the power supply pins on any IC. It helps reduce electrical noise.

It would probably be relatively straight-forward to design a multiplexer between three geophone inputs and thus have just one amplifier on one pin, but personally I'd just build three amplifiers and connect them to three pins. (Actually, I believe the Arduino multiplexes the analog inputs onto a single ADC internally.)

**Comment by sselbe** [comment]
Great, thanks @olewolf. I actually did just build the three amps and will just connect to other analog inputs. I appreciate all the great documentation on this project.
