### ISSUE TITLE
no file or directory

### ISSUE THREAD

**Issue by eliyafariha** [olewolf/geophone#5]
How to solve this prob?

Geophone.ino:98:36: fatal error: twiddle_factors_256_br.h: No such file or directory
compilation terminated.
Error compiling.

**Comment by olewolf** [comment]
I can't reproduce the problem. Please describe your exact steps to reproduce the problem from pulling from Github through opening the project and selecting the correct processor to pressing the compilation.

**Comment by eliyafariha** [comment]
already solved. thank you.👍
